const data = [
    {
        id: 1,
        name: "Gênesis",
        author: "Autor: Moisés.",
        purpose: "Propósito: Ensinar os israelistas o propósito de Deus para eles como uma nação.",
        date: "Data: 1446-1406 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 5 livros que compõem o Pentateuco.",
        acronym: "Gn",
        percentage: 0,
        chapters: Array.from({ length: 50 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 2,
        name: "Êxodo",
        author: "Autor: Moisés.",
        purpose: "Propósito: Confirmar a autoridade divina da liderança de Moisés e estabelecer as regras para a adoração.",
        date: "Data: 1446-1406 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 5 livros que compõem o Pentateuco.",
        acronym: "Êx",
        percentage: 0,
        chapters: Array.from({ length: 40 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 3,
        name: "Levítico",
        author: "Autor: Moisés.",
        purpose: "Propósito: Conduzir os israelitas nos caminhos da santidade para que eles se mantivessem separados do mundo.",
        date: "Data: 1446-1406 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 5 livros que compõem o Pentateuco.",
        acronym: "Lv",
        percentage: 0,
        chapters: Array.from({ length: 27 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 4,
        name: "Números",
        author: "Autor: Moisés.",
        purpose: "Propósito: Conduzir a segunda geração do êxodo na conquista da Terra Prometida, evitando os erros do passado e permanecendo fiéis a Deus.",
        date: "Data: 1406 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 5 livros que compõem o Pentateuco.",
        acronym: "Nm",
        percentage: 0,
        chapters: Array.from({ length: 36 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 5,
        name: "Deuteronômio",
        author: "Autor: Moisés.",
        purpose: "Propósito: Estimular uma renovação da aliança com Deus, antes da entrada na Terra Prometida sob a liderança de Josué.",
        date: "Data: 1406 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 5 livros que compõem o Pentateuco.",
        acronym: "Dt",
        percentage: 0,
        chapters: Array.from({ length: 34 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 6,
        name: "Josué",
        author: "Autor: Desconhecido.",
        purpose: "Propósito: Ensinar às gerações futuras de Israel como servir ao Senhor, tanto nas batalhas como na distribuição da Terra Prometida entre as tribos.",
        date: "Data: 1000-561 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 12 livros históricos do Antigo Testamento.",
        acronym: "Js",
        percentage: 0,
        chapters: Array.from({ length: 24 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 7,
        name: "Juízes",
        author: "Autor: Desconhecido.",
        purpose: "Propósito: Demonstrar a necessidade que Israel tinha de um rei piedoso que seria escolhido por Deus.",
        date: "Data: 1000-538 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 12 livros históricos do Antigo Testamento.",
        acronym: "Jz",
        percentage: 0,
        chapters: Array.from({ length: 21 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 8,
        name: "Rute",
        author: "Autor: Desconhecido.",
        purpose: "Propósito: Demonstrar a legitimidade do reinado de Davi, apesar de sua ancestral moabita, Rute.",
        date: "Data: Cerca de 1000 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 12 livros históricos do Antigo Testamento.",
        acronym: "Rt",
        percentage: 0,
        chapters: Array.from({ length: 4 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 9,
        name: "1 Samuel",
        author: "Autor: Desconhecido.",
        purpose: "Propósito: Explicar que a dinastia de Davi seria a esperança para o futuro de Israel, apesar dos erros cometidos.",
        date: "Data: 930-538 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 12 livros históricos do Antigo Testamento.",
        acronym: "1Sm",
        percentage: 0,
        chapters: Array.from({ length: 31 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 10,
        name: "2 Samuel",
        author: "Autor: Desconhecido.",
        purpose: "Propósito: Explicar que a dinastia de Davi seria a esperança para o futuro de Israel, apesar dos erros cometidos.",
        date: "Data: 930-538 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 12 livros históricos do Antigo Testamento.",
        acronym: "2Sm",
        percentage: 0,
        chapters: Array.from({ length: 24 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 11,
        name: "1 Reis",
        author: "Autor: Desconhecido.",
        purpose: "Propósito: Mostrar a justiça de Deus e chamar o povo ao arrependimento para que eles pudessem regressar do exílio.",
        date: "Data: 560-550 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 12 livros históricos do Antigo Testamento.",
        acronym: "1Rs",
        percentage: 0,
        chapters: Array.from({ length: 22 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 12,
        name: "2 Reis",
        author: "Autor: Desconhecido.",
        purpose: "Propósito: Mostrar a justiça de Deus e chamar o povo ao arrependimento para que eles pudessem regressar do exílio.",
        date: "Data: 560-550 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 12 livros históricos do Antigo Testamento.",
        acronym: "2Rs",
        percentage: 0,
        chapters: Array.from({ length: 25 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 13,
        name: "1 Crônicas",
        author: "Autor: Desconhecido.",
        purpose: "Propósito: Orientar a restauração do reino após o exílio.",
        date: "Data: 520-400 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 12 livros históricos do Antigo Testamento.",
        acronym: "1Cr",
        percentage: 0,
        chapters: Array.from({ length: 29 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 14,
        name: "2 Crônicas",
        author: "Autor: Desconhecido.",
        purpose: "Propósito: Orientar a restauração do reino após o exílio.",
        date: "Data: 520-400 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 12 livros históricos do Antigo Testamento.",
        acronym: "2Cr",
        percentage: 0,
        chapters: Array.from({ length: 36 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 15,
        name: "Esdras",
        author: "Autor: Desconhecido.",
        purpose: "Propósito: Incentivar aqueles que haviam voltado à Terra Prometida a continuar o trabalho iniciado por Zorobabel, Esdras e Neemias.",
        date: "Data: 430-400 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 12 livros históricos do Antigo Testamento.",
        acronym: "Ed",
        percentage: 0,
        chapters: Array.from({ length: 10 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 16,
        name: "Neemias",
        author: "Autor: Desconhecido.",
        purpose: "Propósito: Incentivar aqueles que haviam voltado à Terra Prometida a continuar o trabalho iniciado por Zorobabel, Esdras e Neemias.",
        date: "Data: 430-400 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 12 livros históricos do Antigo Testamento.",
        acronym: "Ne",
        percentage: 0,
        chapters: Array.from({ length: 13 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 17,
        name: "Ester",
        author: "Autor: Desconhecido.",
        purpose: "Propósito: Registrar o livramento que Deus proporcionou ao seu povo.",
        date: "Data: 460-350 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 12 livros históricos do Antigo Testamento.",
        acronym: "Et",
        percentage: 0,
        chapters: Array.from({ length: 10 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 18,
        name: "Jó",
        author: "Autor: Desconhecido.",
        purpose: "Propósito: Explorar os limites e os usos adequados dos provérbios de sabedoria no caso do sofrimento de um justo.",
        date: "Data: 970-586 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 5 livros poéticos do Antigo Testamento.",
        acronym: "Jó",
        percentage: 0,
        chapters: Array.from({ length: 42 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 19,
        name: "Salmos",
        author: "Autores: Moisés, Davi, Salomão, os filhos de Corá, os filhos de Asafe, Etã e vários autores desconhecidos.",
        purpose: "Propósito: Prover para Israel uma coletânea de cânticos para adoração adequada em diversas situações.",
        date: "Data: 1440-400 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 5 livros poéticos do Antigo Testamento.",
        acronym: "Sl",
        percentage: 0,
        chapters: Array.from({ length: 150 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 20,
        name: "Provérbios",
        author: "Autores: Vários, incluindo Salomão, Ezequias, Agur e Lemuel.",
        purpose: "Propósito: Oferecer um recurso para o ensino da sabedoria aos jovens, em primeiro lugar para a família real e, em segundo lugar, para todas as outras famílias de Israel.",
        date: "Data: 960-686 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 5 livros poéticos do Antigo Testamento.",
        acronym: "Pv",
        percentage: 0,
        chapters: Array.from({ length: 31 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 21,
        name: "Eclesiastes",
        author: "Autor: Salomão.",
        purpose: "Propósito: Demonstrar que a vida vista unicamente a partir da perspectiva humana não tem sentido.",
        date: "Data: 930-586 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 5 livros poéticos do Antigo Testamento.",
        acronym: "Ec",
        percentage: 0,
        chapters: Array.from({ length: 12 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 22,
        name: "Cantares",
        author: "Autor: Desconhecido (provavelmente Salomão).",
        purpose: "Propósito: Celebrar a bênção do amor romântico entre marido e esposa.",
        date: "Data: 960-931 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 5 livros poéticos do Antigo Testamento.",
        acronym: "Ct",
        percentage: 0,
        chapters: Array.from({ length: 8 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 23,
        name: "Isaías",
        author: "Autor: Isaías.",
        purpose: "Propósito: Exortar os exilados a se arrependerem de seus pecados e confiarem que o Senhor abençoaria o remanescente fiel.",
        date: "Data: 686-650 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 5 livros dos profetas maiores do Antigo Testamento.",
        acronym: "Is",
        percentage: 0,
        chapters: Array.from({ length: 66 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 24,
        name: "Jeremias",
        author: "Autores: Jeremias e Baruque, seu aluno e/ou escriba.",
        purpose: "Propósito: Lembrar aos exilados os motivos de suas provações e garantir-lhes que, ao se arrependerem, voltariam para a Terra Prometida.",
        date: "Data: 580-539 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 5 livros dos profetas maiores do Antigo Testamento.",
        acronym: "Jr",
        percentage: 0,
        chapters: Array.from({ length: 52 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 25,
        name: "Lamentações",
        author: "Autor: Jeremias.",
        purpose: "Propósito: Expressar o lamento sobre as terríveis condições impostas sobre Jerusalém e sobre o povo de Deus pelos babilônios.",
        date: "Data: 586-516 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 5 livros dos profetas maiores do Antigo Testamento.",
        acronym: "Lm",
        percentage: 0,
        chapters: Array.from({ length: 5 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 26,
        name: "Ezequiel",
        author: "Autor: Ezequiel.",
        purpose: "Propósito: Incentivar os exilados a permanecerem fiéis ao Senhor, para que Ele os conduzisse à Terra Prometida.",
        date: "Data: 593-570 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 5 livros dos profetas maiores do Antigo Testamento.",
        acronym: "Ez",
        percentage: 0,
        chapters: Array.from({ length: 48 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 27,
        name: "Daniel",
        author: "Autor: Daniel.",
        purpose: "Propósito: Dar aos exilados a certeza de que Deus estava no controle da História, e que a Glória de Deus se manifestará no final dos tempos.",
        date: "Data: Imediatamente após 539 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 5 livros dos profetas maiores do Antigo Testamento.",
        acronym: "Dn",
        percentage: 0,
        chapters: Array.from({ length: 12 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 28,
        name: "Oséias",
        author: "Autor: Oséias.",
        purpose: "Propósito: Mostrar o justo julgamento divino através do exílio e garantir ao povo de Deus que uma grande restauração aconteceria após esse período.",
        date: "Data: 760-722 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 12 livros dos profetas menores do Antigo Testamento.",
        acronym: "Os",
        percentage: 0,
        chapters: Array.from({ length: 14 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 29,
        name: "Joel",
        author: "Autor: Joel.",
        purpose: "Propósito: Chamar o povo de Deus ao arrependimento para que possa escapar do juízo e confiar na chegada do Dia do Senhor.",
        date: "Data: Desconhecida.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 12 livros dos profetas menores do Antigo Testamento.",
        acronym: "Jl",
        percentage: 0,
        chapters: Array.from({ length: 3 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 30,
        name: "Amós",
        author: "Autor: Amós.",
        purpose: "Propósito: Revelar a seriedade do julgamento divino por causa da infidelidade em Israel e Judá e declarar que estava próxima a restauração depois da destruição e do exílio.",
        date: "Data: 760-750 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 12 livros dos profetas menores do Antigo Testamento.",
        acronym: "Am",
        percentage: 0,
        chapters: Array.from({ length: 9 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 31,
        name: "Obadias",
        author: "Autor: Obadias.",
        purpose: "Propósito: Trazer ao povo de Judá, que enfrentava adversidades, esperança na justiça divina e na vitória final sobre todos os inimigos.",
        date: "Data: 586 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 12 livros dos profetas menores do Antigo Testamento.",
        acronym: "Ob",
        percentage: 0,
        chapters: Array.from({ length: 1 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 32,
        name: "Jonas",
        author: "Autor: Desconhecido.",
        purpose: "Propósito: Encorajar os israelitas a atenderem ao chamado de Deus para estender sua misericórdia às nações.",
        date: "Data: 750-613 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 12 livros dos profetas menores do Antigo Testamento.",
        acronym: "Jn",
        percentage: 0,
        chapters: Array.from({ length: 4 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 33,
        name: "Miquéias",
        author: "Autor: Miquéias.",
        purpose: "Propósito: Chamar Judá ao arrependimento e prepará-los para o exílio babilônico.",
        date: "Data: 742-686 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 12 livros dos profetas menores do Antigo Testamento.",
        acronym: "Mq",
        percentage: 0,
        chapters: Array.from({ length: 7 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 34,
        name: "Naum",
        author: "Autor: Naum.",
        purpose: "Propósito: Confortar Judá ao anunciar julgamentos futuros contra Nínive.",
        date: "Data: 663-612 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 12 livros dos profetas menores do Antigo Testamento.",
        acronym: "Na",
        percentage: 0,
        chapters: Array.from({ length: 3 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 35,
        name: "Habacuque",
        author: "Autor: Habacuque.",
        purpose: "Propósito: Guiar Israel em direção à fé em Deus durante as provações do exílio babilônico.",
        date: "Data: 605-600 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 12 livros dos profetas menores do Antigo Testamento.",
        acronym: "Hc",
        percentage: 0,
        chapters: Array.from({ length: 3 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 36,
        name: "Sofonias",
        author: "Autor: Sofonias.",
        purpose: "Propósito: Convocar o povo de Judá ao arrependimento em face da invasão babilônica, bem como à esperança numa grande restauração após o tempo de destruição e exílio.",
        date: "Data: 640-621 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 12 livros dos profetas menores do Antigo Testamento.",
        acronym: "Sf",
        percentage: 0,
        chapters: Array.from({ length: 3 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 37,
        name: "Ageu",
        author: "Autor: Ageu.",
        purpose: "Propósito: Incentivar a reconstrução do templo na esperança de trazer grandes bençãos para Israel depois do exílio.",
        date: "Data: 520 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 12 livros dos profetas menores do Antigo Testamento.",
        acronym: "Ag",
        percentage: 0,
        chapters: Array.from({ length: 2 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 38,
        name: "Zacarias",
        author: "Autor: Zacarias.",
        purpose: "Propósito: Encorajar o povo a crer nas grandes bençãos prometidas para Jerusalém quando o reino de Deus vier em sua plenitude.",
        date: "Data: 520-475 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 12 livros dos profetas menores do Antigo Testamento.",
        acronym: "Zc",
        percentage: 0,
        chapters: Array.from({ length: 14 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 39,
        name: "Malaquias",
        author: "Autor: Malaquias.",
        purpose: "Propósito: Trazer ânimo aos que voltaram do exílio para uma fé renovada por meio do anúncio da vinda do julgamento do Messias.",
        date: "Data: 458-433 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 12 livros dos profetas menores do Antigo Testamento.",
        acronym: "Ml",
        percentage: 0,
        chapters: Array.from({ length: 4 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 40,
        name: "Mateus",
        author: "Autor: Mateus.",
        purpose: "Propósito: Apresentar Jesus como o tão esperado rei e inspirar os cristãos a promover seu reino.",
        date: "Data: 60-70 d.C.",
        public: "Público alvo: Judeus.",
        presentation: "Jesus é apresentado como: Rei.",
        emphasis: "Ênfase: A soberania de Jesus.",
        observation: "Observação: Um dos 3 evangelhos sinópticos do Novo Testamento.",
        acronym: "Mt",
        percentage: 0,
        chapters: Array.from({ length: 28 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 41,
        name: "Marcos",
        author: "Autor: João Marcos.",
        purpose: "Propósito: Apresentar as boas-novas de Jesus aos gentios por meio dos fatos notáveis sobre a vida, a morte e a ressurreição de Jesus.",
        date: "Data: 62-69 d.C. ou pouco antes.",
        public: "Público alvo: Romanos.",
        presentation: "Jesus é apresentado como: Servo.",
        emphasis: "Ênfase: O ministério de Jesus.",
        observation: "Observação: Um dos 3 evangelhos sinópticos do Novo Testamento.",
        acronym: "Mc",
        percentage: 0,
        chapters: Array.from({ length: 16 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 42,
        name: "Lucas",
        author: "Autor: Lucas.",
        purpose: "Propósito: Apresentar um relato fiel e organizado a respeito do ministério de Jesus, preparando a Igreja para a pregação de arrependimento e perdão em nome de Jesus para todas as nações.",
        date: "Data: 60-63 d.C.",
        public: "Público alvo: Gregos.",
        presentation: "Jesus é apresentado como: Homem.",
        emphasis: "Ênfase: A humanidade de Jesus.",
        observation: "Observação: Um dos 3 evangelhos sinópticos do Novo Testamento.",
        acronym: "Lc",
        percentage: 0,
        chapters: Array.from({ length: 24 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 43,
        name: "João",
        author: "Autor: O apóstolo João.",
        purpose: "Propósito: Apresentar a vida de Jesus de tal modo que os incrédulos possam ir a ele pela fé e os cristãos possam desenvolver sua fé em Cristo como o Messias e o Filho de Deus que desceu do céu.",
        date: "Data: 85-90 d.C.",
        public: "Público alvo: Todos.",
        presentation: "Jesus é apresentado como: Deus.",
        emphasis: "Ênfase: A divindade de Jesus.",
        observation: null,
        acronym: "Jo",
        percentage: 0,
        chapters: Array.from({ length: 21 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 44,
        name: "Atos dos Apóstolos",
        author: "Autor: Lucas.",
        purpose: "Propósito: Orientar a igreja em sua missão permanente por meio do relato de como o Espírito Santo capacitou os apóstolos para propagar o testemunho de Cristo ao mundo.",
        date: "Data: 60-64 d.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Único livro histórico do Novo Testamento.",
        acronym: "At",
        percentage: 0,
        chapters: Array.from({ length: 28 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 45,
        name: "Romanos",
        author: "Autor: O apóstolo Paulo.",
        purpose: "Propósito: Apresentar a mensagem do evangelho aos crentes em Roma, e explicar como esse evangelho corrige as divisões entre os crentes judeus e não-judeus.",
        date: "Data: 55-57 d.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Uma das 21 Epístolas do Novo Testamento.",
        acronym: "Rm",
        percentage: 0,
        chapters: Array.from({ length: 16 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 46,
        name: "1 Coríntios",
        author: "Autor: O apóstolo Paulo.",
        purpose: "Propósito: Combater a rebeldia, as divisões e a falta de amor que tinham sido causadas pelo orgulho e presunção na igreja de Corinto.",
        date: "Data: 55 d.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Uma das 21 Epístolas do Novo Testamento.",
        acronym: "1Co",
        percentage: 0,
        chapters: Array.from({ length: 16 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 47,
        name: "2 Coríntios",
        author: "Autor: O apóstolo Paulo.",
        purpose: "Propósito: Expressar carinho e gratidão pelo arrependimento que houve em Corinto e encorajar uma maior lealdade a Paulo como um apóstolo de Cristo.",
        date: "Data: 55 d.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Uma das 21 Epístolas do Novo Testamento.",
        acronym: "2Co",
        percentage: 0,
        chapters: Array.from({ length: 13 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 48,
        name: "Gálatas",
        author: "Autor: O apóstolo Paulo.",
        purpose: "Propósito: Auxiliar os cristãos da Galácia a resistir aos falsos mestres que pregavam que a salvação também dependia do mérito humano na obediência à lei.",
        date: "Data: 49-55 d.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Uma das 21 Epístolas do Novo Testamento.",
        acronym: "Gl",
        percentage: 0,
        chapters: Array.from({ length: 6 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 49,
        name: "Efésios",
        author: "Autor: O apóstolo Paulo.",
        purpose: "Propósito: Ensinar os cristãos em Éfeso sobre a benção e as implicações práticas de ser a Igreja em Cristo.",
        date: "Data: 60-62 d.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Uma das 21 Epístolas do Novo Testamento.",
        acronym: "Ef",
        percentage: 0,
        chapters: Array.from({ length: 6 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 50,
        name: "Filipenses",
        author: "Autor: O apóstolo Paulo.",
        purpose: "Propósito: Agradecer aos filipenses pela solidariedade enquanto esteve na prisão e animá-los a se unirem e a se ajudarem mutuamente em Cristo.",
        date: "Data: 61 d.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Uma das 21 Epístolas do Novo Testamento.",
        acronym: "Fp",
        percentage: 0,
        chapters: Array.from({ length: 4 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 51,
        name: "Colossenses",
        author: "Autor: O apóstolo Paulo.",
        purpose: "Propósito: Afirmar e explicar a supremacia e suficiência de Cristo em oposição a todos os outros poderes e tentativas para se obter a salvação.",
        date: "Data: 60 d.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Uma das 21 Epístolas do Novo Testamento.",
        acronym: "Cl",
        percentage: 0,
        chapters: Array.from({ length: 4 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 52,
        name: "1 Tessalonicenses",
        author: "Autor: O apóstolo Paulo.",
        purpose: "Propósito: Assegurar aos cristãos tessalonicenses o amor que Paulo tinha por eles e instruí-los a respeito da importância de viver para Cristo e entender corretamente as etapas do seu retorno.",
        date: "Data: 50-51 d.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Uma das 21 Epístolas do Novo Testamento.",
        acronym: "1Ts",
        percentage: 0,
        chapters: Array.from({ length: 5 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 53,
        name: "2 Tessalonicenses",
        author: "Autor: O apóstolo Paulo.",
        purpose: "Propósito: Contemplar a sua carta anterior, dando aos tessalonicenses instruções adicionais sobre a vinda de Cristo e a importância de um viver diário responsável.",
        date: "Data: 50-52 d.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Uma das 21 Epístolas do Novo Testamento.",
        acronym: "2Ts",
        percentage: 0,
        chapters: Array.from({ length: 3 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 54,
        name: "1 Timóteo",
        author: "Autor: O apóstolo Paulo.",
        purpose: "Propósito: Orientar Timóteo em sua oposição aos falsos mestres em Éfeso.",
        date: "Data: 62-64 d.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Uma das 21 Epístolas do Novo Testamento.",
        acronym: "1Tm",
        percentage: 0,
        chapters: Array.from({ length: 6 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 55,
        name: "2 Timóteo",
        author: "Autor: O apóstolo Paulo.",
        purpose: "Propósito: Convidar Timóteo para visitar Paulo em seus últimos dias e animar Timóteo em seu ministério contra os falsos mestres em Éfeso.",
        date: "Data: 64-68 d.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Uma das 21 Epístolas do Novo Testamento.",
        acronym: "2Tm",
        percentage: 0,
        chapters: Array.from({ length: 4 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 56,
        name: "Tito",
        author: "Autor: O apóstolo Paulo.",
        purpose: "Propósito: Incentivar Tito a completar a organização das igrejas em Creta, confrontar as ações de falsos mestres nessa região e instruir os crentes a terem uma conduta cristã apropriada.",
        date: "Data: 62-64 d.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Uma das 21 Epístolas do Novo Testamento.",
        acronym: "Tt",
        percentage: 0,
        chapters: Array.from({ length: 3 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 57,
        name: "Filemom",
        author: "Autor: O apóstolo Paulo.",
        purpose: "Propósito: Interceder em favor de Onésimo, um escravo fugitivo.",
        date: "Data: cerca de 60 d.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Uma das 21 Epístolas do Novo Testamento.",
        acronym: "Fm",
        percentage: 0,
        chapters: Array.from({ length: 1 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 58,
        name: "Hebreus",
        author: "Autor: Desconhecidoo.",
        purpose: "Propósito: Incentivar a fidelidade a Cristo e à sua nova aliança, mostrando que ele é o novo, último e superior sumo sacerdote.",
        date: "Data: antes de 70 d.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Uma das 21 Epístolas do Novo Testamento.",
        acronym: "Hb",
        percentage: 0,
        chapters: Array.from({ length: 13 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 59,
        name: "Tiago",
        author: "Autor: Tiago, o irmão de Jesus.",
        purpose: "Propósito: Ensinar a sabedoria de Deus para perseverar em meio às dificuldades até o retorno de Cristo.",
        date: "Data: 44-62 d.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Uma das 21 Epístolas do Novo Testamento.",
        acronym: "Tg",
        percentage: 0,
        chapters: Array.from({ length: 5 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 60,
        name: "1 Pedro",
        author: "Autor: O apóstolo Pedro.",
        purpose: "Propósito: Encorajar os cristãos perseguidos e confusos a permanecerem unidos e firmes na fé, muito mais valiosa do que o ouro.",
        date: "Data: 60-68 d.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Uma das 21 Epístolas do Novo Testamento.",
        acronym: "1Pe",
        percentage: 0,
        chapters: Array.from({ length: 5 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 61,
        name: "2 Pedro",
        author: "Autor: O apóstolo Pedro.",
        purpose: "Propósito: Encorajar o crescimento espiritual, alertar sobre o surgimento de zombadores e falsos mestres, e afirmar a certeza do retorno de Cristo.",
        date: "Data: 65-67 d.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Uma das 21 Epístolas do Novo Testamento.",
        acronym: "2Pe",
        percentage: 0,
        chapters: Array.from({ length: 3 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 62,
        name: "1 João",
        author: "Autor: O apóstolo João.",
        purpose: "Propósito: Afirmar a certeza do perdão em Jesus Cristo, estimular o amor ao próximo, alertar sobre falsos ensinos e o perigo da idolatria.",
        date: "Data: 85-95 d.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Uma das 21 Epístolas do Novo Testamento.",
        acronym: "1Jo",
        percentage: 0,
        chapters: Array.from({ length: 5 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 63,
        name: "2 João",
        author: "Autor: O apóstolo João.",
        purpose: "Propósito: Alertar os cristãos com respeito ao falso ensino de que Cristo não tinha vindo verdadeiramente em carne e incentivar a hospitalidade aos pregadores do verdadeiro evangelho.",
        date: "Data: 85-95 d.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Uma das 21 Epístolas do Novo Testamento.",
        acronym: "2Jo",
        percentage: 0,
        chapters: Array.from({ length: 1 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 64,
        name: "3 João",
        author: "Autor: O apóstolo João.",
        purpose: "Propósito: Incentivar o serviço ao próximo, especialmente a hospitalidade àqueles que ministram o evangelho.",
        date: "Data: 80-90 d.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Uma das 21 Epístolas do Novo Testamento.",
        acronym: "3Jo",
        percentage: 0,
        chapters: Array.from({ length: 1 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 65,
        name: "Judas",
        author: "Autor: Judas, o irmão de Jesus.",
        purpose: "Propósito: Combater o falso ensino de que a liberdade e a salvação dos cristãos pela graça dão a eles licença para pecar.",
        date: "Data: 65-67 d.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Uma das 21 Epístolas do Novo Testamento.",
        acronym: "Jd",
        percentage: 0,
        chapters: Array.from({ length: 1 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 66,
        name: "Apocalipse",
        author: "Autor: O apóstolo João.",
        purpose: "Propósito: Estimular a fidelidade a Cristo em meio ao sofrimento, demonstrar que Deus tem o controle da História. Revelar a gloriosa manifestação do seu Reino e a consumação de todas as coisas.",
        date: "Data: 66-95 d.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Livro profético que declara vários eventos que em breve vão acontecer.",
        acronym: "Ap",
        percentage: 0,
        chapters: Array.from({ length: 22 }, (_, i) => ({ number: i + 1, read: false}))
    }
];

export default data;