const data = [
    {
        id: 1,
        name: "Gênesis",
        author: "Autor: Moisés.",
        purpose: "Propósito: Ensinar os israelistas o propósito de Deus para eles como uma nação.",
        date: "Data: 1446-1406 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 5 livros que compõem o Pentateuco.",
        acronym: "Gn",
        percentage: 0,
        chapters: Array.from({ length: 50 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 2,
        name: "Êxodo",
        author: "Autor: Moisés.",
        purpose: "Propósito: Confirmar a autoridade divina da liderança de Moisés e estabelecer as regras para a adoração.",
        date: "Data: 1446-1406 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 5 livros que compõem o Pentateuco.",
        acronym: "Êx",
        percentage: 0,
        chapters: Array.from({ length: 40 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 3,
        name: "Levítico",
        author: "Autor: Moisés.",
        purpose: "Propósito: Conduzir os israelitas nos caminhos da santidade para que eles se mantivessem separados do mundo.",
        date: "Data: 1446-1406 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 5 livros que compõem o Pentateuco.",
        acronym: "Lv",
        percentage: 0,
        chapters: Array.from({ length: 27 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 4,
        name: "Números",
        author: "Autor: Moisés.",
        purpose: "Propósito: Conduzir a segunda geração do êxodo na conquista da Terra Prometida, evitando os erros do passado e permanecendo fiéis a Deus.",
        date: "Data: 1406 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 5 livros que compõem o Pentateuco.",
        acronym: "Nm",
        percentage: 0,
        chapters: Array.from({ length: 36 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 5,
        name: "Deuteronômio",
        author: "Autor: Moisés.",
        purpose: "Propósito: Estimular uma renovação da aliança com Deus, antes da entrada na Terra Prometida sob a liderança de Josué.",
        date: "Data: 1406 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 5 livros que compõem o Pentateuco.",
        acronym: "Dt",
        percentage: 0,
        chapters: Array.from({ length: 34 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 6,
        name: "Josué",
        author: "Autor: Desconhecido.",
        purpose: "Propósito: Ensinar às gerações futuras de Israel como servir ao Senhor, tanto nas batalhas como na distribuição da Terra Prometida entre as tribos.",
        date: "Data: 1000-561 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 12 livros históricos do Antigo Testamento.",
        acronym: "Js",
        percentage: 0,
        chapters: Array.from({ length: 24 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 7,
        name: "Juízes",
        author: "Autor: Desconhecido.",
        purpose: "Propósito: Demonstrar a necessidade que Israel tinha de um rei piedoso que seria escolhido por Deus.",
        date: "Data: 1000-538 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 12 livros históricos do Antigo Testamento.",
        acronym: "Jz",
        percentage: 0,
        chapters: Array.from({ length: 21 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 8,
        name: "Rute",
        author: "Autor: Desconhecido.",
        purpose: "Propósito: Demonstrar a legitimidade do reinado de Davi, apesar de sua ancestral moabita, Rute.",
        date: "Data: Cerca de 1000 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 12 livros históricos do Antigo Testamento.",
        acronym: "Rt",
        percentage: 0,
        chapters: Array.from({ length: 4 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 9,
        name: "1 Samuel",
        author: "Autor: Desconhecido.",
        purpose: "Propósito: Explicar que a dinastia de Davi seria a esperança para o futuro de Israel, apesar dos erros cometidos.",
        date: "Data: 930-538 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 12 livros históricos do Antigo Testamento.",
        acronym: "1Sm",
        percentage: 0,
        chapters: Array.from({ length: 31 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 10,
        name: "2 Samuel",
        author: "Autor: Desconhecido.",
        purpose: "Propósito: Explicar que a dinastia de Davi seria a esperança para o futuro de Israel, apesar dos erros cometidos.",
        date: "Data: 930-538 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 12 livros históricos do Antigo Testamento.",
        acronym: "2Sm",
        percentage: 0,
        chapters: Array.from({ length: 24 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 11,
        name: "1 Reis",
        author: "Autor: Desconhecido.",
        purpose: "Propósito: Mostrar a justiça de Deus e chamar o povo ao arrependimento para que eles pudessem regressar do exílio.",
        date: "Data: 560-550 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 12 livros históricos do Antigo Testamento.",
        acronym: "1Rs",
        percentage: 0,
        chapters: Array.from({ length: 22 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 12,
        name: "2 Reis",
        author: "Autor: Desconhecido.",
        purpose: "Propósito: Mostrar a justiça de Deus e chamar o povo ao arrependimento para que eles pudessem regressar do exílio.",
        date: "Data: 560-550 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 12 livros históricos do Antigo Testamento.",
        acronym: "2Rs",
        percentage: 0,
        chapters: Array.from({ length: 25 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 13,
        name: "1 Crônicas",
        author: "Autor: Desconhecido.",
        purpose: "Propósito: Orientar a restauração do reino após o exílio.",
        date: "Data: 520-400 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 12 livros históricos do Antigo Testamento.",
        acronym: "1Cr",
        percentage: 0,
        chapters: Array.from({ length: 29 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 14,
        name: "2 Crônicas",
        author: "Autor: Desconhecido.",
        purpose: "Propósito: Orientar a restauração do reino após o exílio.",
        date: "Data: 520-400 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 12 livros históricos do Antigo Testamento.",
        acronym: "2Cr",
        percentage: 0,
        chapters: Array.from({ length: 36 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 15,
        name: "Esdras",
        author: "Autor: Desconhecido.",
        purpose: "Propósito: Incentivar aqueles que haviam voltado à Terra Prometida a continuar o trabalho iniciado por Zorobabel, Esdras e Neemias.",
        date: "Data: 430-400 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 12 livros históricos do Antigo Testamento.",
        acronym: "Ed",
        percentage: 0,
        chapters: Array.from({ length: 10 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 16,
        name: "Neemias",
        author: "Autor: Desconhecido.",
        purpose: "Propósito: Incentivar aqueles que haviam voltado à Terra Prometida a continuar o trabalho iniciado por Zorobabel, Esdras e Neemias.",
        date: "Data: 430-400 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 12 livros históricos do Antigo Testamento.",
        acronym: "Ne",
        percentage: 0,
        chapters: Array.from({ length: 13 }, (_, i) => ({ number: i + 1, read: false}))
    },
    {
        id: 17,
        name: "Ester",
        author: "Autor: Desconhecido.",
        purpose: "Propósito: Registrar o livramento que Deus proporcionou ao seu povo.",
        date: "Data: 460-350 a.C.",
        public: null,
        presentation: null,
        emphasis: null,
        observation: "Observação: Um dos 12 livros históricos do Antigo Testamento.",
        acronym: "Et",
        percentage: 0,
        chapters: Array.from({ length: 10 }, (_, i) => ({ number: i + 1, read: false}))
    },
];

export default data;